import * as Popover from '@radix-ui/react-popover'
import { isValidElement, useId, useRef, useState, type KeyboardEvent as ReactKeyboardEvent, type ReactElement, type ReactNode } from 'react'
import Icon from '../common/Icon.tsx'
export interface SelectOption { readonly value: string; readonly label: string; readonly provider?: string }
/** Searchable controlled selection surface; Radix owns portal, dismissal, and focus restoration. */
export function Select({ value, options, onChange, disabled = false, label, triggerClassName = '', renderTrigger }: { readonly value: string; readonly options: readonly SelectOption[]; readonly onChange: (value: string) => void; readonly disabled?: boolean; readonly label?: string; readonly triggerClassName?: string; readonly renderTrigger?: (current: SelectOption | undefined, open: boolean) => ReactNode }) {
  const [open, setOpen] = useState(false), [query, setQuery] = useState(''), [active, setActive] = useState(0)
  const triggerRef = useRef<HTMLButtonElement | null>(null), id = useId(), current = options.find((option) => option.value === value), visible = options.filter((option) => option.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())), searchable = options.length > 8
  const pick = (index: number) => { const option = visible[index]; if (!option) return; onChange(option.value); setOpen(false); triggerRef.current?.focus() }
  const onKeyDown = (event: ReactKeyboardEvent) => { if (!open) { if (!disabled && ['ArrowDown', 'ArrowUp'].includes(event.key)) { event.preventDefault(); setOpen(true) }; return }; if (event.key === 'Escape') { event.preventDefault(); setOpen(false) } else if (event.key === 'ArrowDown') { event.preventDefault(); setActive((n) => Math.min(n + 1, visible.length - 1)) } else if (event.key === 'ArrowUp') { event.preventDefault(); setActive((n) => Math.max(n - 1, 0)) } else if (event.key === 'Enter' && !event.nativeEvent.isComposing) { event.preventDefault(); pick(active) } }
  const renderedTrigger = renderTrigger?.(current, open)
  const trigger = renderTrigger !== undefined && isValidElement(renderedTrigger)
    ? renderedTrigger as ReactElement
    : <button type="button" ref={triggerRef} className={`ui-select-trigger ${triggerClassName}`} disabled={disabled} aria-label={label} aria-haspopup="listbox" title={current?.label ?? value}><span className="ui-select-value">{current?.label ?? value}</span><Icon name="chevron" size={12} className={`chevron ${open ? 'chevron-up' : ''}`} /></button>
  return <Popover.Root open={open} onOpenChange={(next) => { setOpen(next); if (next) { setQuery(''); setActive(Math.max(0, options.findIndex((option) => option.value === value))) } }}><div className="ui-select" onKeyDown={onKeyDown}><Popover.Trigger asChild>{trigger}</Popover.Trigger><Popover.Portal><Popover.Content className="ui-menu" sideOffset={6} collisionPadding={8}>{searchable ? <input className="select-search" value={query} placeholder="Search providers or models…" role="combobox" aria-label={`Search ${label ?? 'options'}`} aria-controls={id} onChange={(event) => { setQuery(event.target.value); setActive(0) }} /> : null}<ul id={id} role="listbox" aria-label={label} className="select-options">{visible.map((option, index) => <li key={option.value} role="presentation">{option.provider && option.provider !== visible[index - 1]?.provider ? <div className="select-group">{option.provider}</div> : null}<button type="button" role="option" tabIndex={-1} aria-selected={option.value === value} className={`ui-option ${option.value === value ? 'ui-option-selected' : ''} ${index === active ? 'ui-option-active' : ''}`} onMouseEnter={() => setActive(index)} onClick={() => pick(index)}>{option.label}</button></li>)}</ul>{visible.length === 0 ? <p className="select-group" role="status">No results</p> : null}</Popover.Content></Popover.Portal></div></Popover.Root>
}
